# Generated by Django 2.2.3 on 2020-12-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя покемона')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название на английском')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='Название на японском')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolutions', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционирует')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Ширина')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(null=True, verbose_name='Появится')),
                ('disappeared_at', models.DateTimeField(null=True, verbose_name='Исчезнет')),
                ('level', models.IntegerField(null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(null=True, verbose_name='Сила')),
                ('defence', models.IntegerField(null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
